---

plugins:
  - jest

parser: 'babel-eslint'

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

env:
  jest: true
  node: true

rules:
  no-console: 0
  no-nested-ternary: 0
  max-len: ["error", { "ignoreComments": true }]
  no-bitwise: ["error", { "allow": [">>>", "^"] }]
